name: Add competitor to list with issue

on:
  issues:
    types: [labeled]
jobs:
    
  add-competitor:
    if: ${{ contains(github.event.issue.labels.*.name, 'participation') && contains(github.event.issue.labels.*.name, 'accepted') }}

    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
        
      - name: Add competitor to file
        run: echo '${{ github.event.issue.body }}'
