name: Add competitor to list with issue

on:
  issues:
    types: [labeled]
jobs:
  add-competitor:

    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
